//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dime.WSP {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://servicios.generacionencuestas.claro.com/", ConfigurationName="WSP.GeneracionEncuesta")]
    internal interface GeneracionEncuesta {
        
        // CODEGEN: El parámetro 'RespGenerarEncuesta' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.generacionencuestas.claro.com/GeneracionEncuesta/enviarEncuestaR" +
            "equest", ReplyAction="http://servicios.generacionencuestas.claro.com/GeneracionEncuesta/enviarEncuestaR" +
            "esponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="RespGenerarEncuesta")]
        Dime.WSP.enviarEncuestaResponse enviarEncuesta(Dime.WSP.enviarEncuestaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.generacionencuestas.claro.com/GeneracionEncuesta/enviarEncuestaR" +
            "equest", ReplyAction="http://servicios.generacionencuestas.claro.com/GeneracionEncuesta/enviarEncuestaR" +
            "esponse")]
        System.Threading.Tasks.Task<Dime.WSP.enviarEncuestaResponse> enviarEncuestaAsync(Dime.WSP.enviarEncuestaRequest request);
        
        // CODEGEN: El parámetro 'RespGenerarLog' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.generacionencuestas.claro.com/GeneracionEncuesta/registrarLogReq" +
            "uest", ReplyAction="http://servicios.generacionencuestas.claro.com/GeneracionEncuesta/registrarLogRes" +
            "ponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="RespGenerarLog")]
        Dime.WSP.registrarLogResponse registrarLog(Dime.WSP.registrarLogRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.generacionencuestas.claro.com/GeneracionEncuesta/registrarLogReq" +
            "uest", ReplyAction="http://servicios.generacionencuestas.claro.com/GeneracionEncuesta/registrarLogRes" +
            "ponse")]
        System.Threading.Tasks.Task<Dime.WSP.registrarLogResponse> registrarLogAsync(Dime.WSP.registrarLogRequest request);
        
        // CODEGEN: El parámetro 'Respuesta' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.generacionencuestas.claro.com/GeneracionEncuesta/resetPropiedade" +
            "sRequest", ReplyAction="http://servicios.generacionencuestas.claro.com/GeneracionEncuesta/resetPropiedade" +
            "sResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Respuesta")]
        Dime.WSP.resetPropiedadesResponse resetPropiedades(Dime.WSP.resetPropiedadesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.generacionencuestas.claro.com/GeneracionEncuesta/resetPropiedade" +
            "sRequest", ReplyAction="http://servicios.generacionencuestas.claro.com/GeneracionEncuesta/resetPropiedade" +
            "sResponse")]
        System.Threading.Tasks.Task<Dime.WSP.resetPropiedadesResponse> resetPropiedadesAsync(Dime.WSP.resetPropiedadesRequest request);
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicios.generacionencuestas.claro.com/")]
    public partial class reqGenerarEncuesta : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idtransaccionField;
        
        private int idEncuestaField;
        
        private bool idEncuestaFieldSpecified;
        
        private string canalField;
        
        private string subCanalField;
        
        private string zonaField;
        
        private string fechaAtencionClienteField;
        
        private string fechaEnvioEncuestaField;
        
        private string fechaReenvioEncuestaField;
        
        private string minField;
        
        private string minContactoField;
        
        private string minOrigenField;
        
        private string emailField;
        
        private string cuentaField;
        
        private string operacionField;
        
        private string tokenIdField;
        
        private string usuarioRegistraField;
        
        private string enviaReintentoField;
        
        private string enviaSoloEmailField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string idtransaccion {
            get {
                return this.idtransaccionField;
            }
            set {
                this.idtransaccionField = value;
                this.RaisePropertyChanged("idtransaccion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idEncuesta {
            get {
                return this.idEncuestaField;
            }
            set {
                this.idEncuestaField = value;
                this.RaisePropertyChanged("idEncuesta");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idEncuestaSpecified {
            get {
                return this.idEncuestaFieldSpecified;
            }
            set {
                this.idEncuestaFieldSpecified = value;
                this.RaisePropertyChanged("idEncuestaSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string canal {
            get {
                return this.canalField;
            }
            set {
                this.canalField = value;
                this.RaisePropertyChanged("canal");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string subCanal {
            get {
                return this.subCanalField;
            }
            set {
                this.subCanalField = value;
                this.RaisePropertyChanged("subCanal");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string zona {
            get {
                return this.zonaField;
            }
            set {
                this.zonaField = value;
                this.RaisePropertyChanged("zona");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string fechaAtencionCliente {
            get {
                return this.fechaAtencionClienteField;
            }
            set {
                this.fechaAtencionClienteField = value;
                this.RaisePropertyChanged("fechaAtencionCliente");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string fechaEnvioEncuesta {
            get {
                return this.fechaEnvioEncuestaField;
            }
            set {
                this.fechaEnvioEncuestaField = value;
                this.RaisePropertyChanged("fechaEnvioEncuesta");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string fechaReenvioEncuesta {
            get {
                return this.fechaReenvioEncuestaField;
            }
            set {
                this.fechaReenvioEncuestaField = value;
                this.RaisePropertyChanged("fechaReenvioEncuesta");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string min {
            get {
                return this.minField;
            }
            set {
                this.minField = value;
                this.RaisePropertyChanged("min");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string minContacto {
            get {
                return this.minContactoField;
            }
            set {
                this.minContactoField = value;
                this.RaisePropertyChanged("minContacto");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string minOrigen {
            get {
                return this.minOrigenField;
            }
            set {
                this.minOrigenField = value;
                this.RaisePropertyChanged("minOrigen");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string cuenta {
            get {
                return this.cuentaField;
            }
            set {
                this.cuentaField = value;
                this.RaisePropertyChanged("cuenta");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string operacion {
            get {
                return this.operacionField;
            }
            set {
                this.operacionField = value;
                this.RaisePropertyChanged("operacion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string tokenId {
            get {
                return this.tokenIdField;
            }
            set {
                this.tokenIdField = value;
                this.RaisePropertyChanged("tokenId");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string usuarioRegistra {
            get {
                return this.usuarioRegistraField;
            }
            set {
                this.usuarioRegistraField = value;
                this.RaisePropertyChanged("usuarioRegistra");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string enviaReintento {
            get {
                return this.enviaReintentoField;
            }
            set {
                this.enviaReintentoField = value;
                this.RaisePropertyChanged("enviaReintento");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string enviaSoloEmail {
            get {
                return this.enviaSoloEmailField;
            }
            set {
                this.enviaSoloEmailField = value;
                this.RaisePropertyChanged("enviaSoloEmail");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicios.generacionencuestas.claro.com/")]
    public partial class RespConsultarParamCobranza : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codigoField;
        
        private string descripcionField;
        
        private string mensajeField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
                this.RaisePropertyChanged("mensaje");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicios.generacionencuestas.claro.com/")]
    public partial class reqGenerarLog : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idTransaccionField;
        
        private string canalField;
        
        private string subCanalField;
        
        private string zonaRegionField;
        
        private string fechaAtencionClienteField;
        
        private string fechaEnvioEncuestaField;
        
        private string fechaReenvioEncuestaField;
        
        private long msisdnField;
        
        private bool msisdnFieldSpecified;
        
        private long minContactoField;
        
        private bool minContactoFieldSpecified;
        
        private int telefonoLineaOrigenField;
        
        private bool telefonoLineaOrigenFieldSpecified;
        
        private string emailField;
        
        private int cuentaField;
        
        private bool cuentaFieldSpecified;
        
        private int coIdField;
        
        private bool coIdFieldSpecified;
        
        private string operacionField;
        
        private string tipoLineaField;
        
        private string segmentoField;
        
        private int tipoIdentificacionField;
        
        private bool tipoIdentificacionFieldSpecified;
        
        private long numeroIdentificacionField;
        
        private bool numeroIdentificacionFieldSpecified;
        
        private string nombreClienteField;
        
        private int estadoField;
        
        private bool estadoFieldSpecified;
        
        private string tokenIdField;
        
        private string causalesNoExitoField;
        
        private int idEncuestaField;
        
        private bool idEncuestaFieldSpecified;
        
        private string nombreEncuestaField;
        
        private int numeroReintentosField;
        
        private bool numeroReintentosFieldSpecified;
        
        private string desReintentoFallidoField;
        
        private string urlConexionField;
        
        private string usuarioRegistraSistemaField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string idTransaccion {
            get {
                return this.idTransaccionField;
            }
            set {
                this.idTransaccionField = value;
                this.RaisePropertyChanged("idTransaccion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string canal {
            get {
                return this.canalField;
            }
            set {
                this.canalField = value;
                this.RaisePropertyChanged("canal");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string subCanal {
            get {
                return this.subCanalField;
            }
            set {
                this.subCanalField = value;
                this.RaisePropertyChanged("subCanal");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string zonaRegion {
            get {
                return this.zonaRegionField;
            }
            set {
                this.zonaRegionField = value;
                this.RaisePropertyChanged("zonaRegion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string FechaAtencionCliente {
            get {
                return this.fechaAtencionClienteField;
            }
            set {
                this.fechaAtencionClienteField = value;
                this.RaisePropertyChanged("FechaAtencionCliente");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string fechaEnvioEncuesta {
            get {
                return this.fechaEnvioEncuestaField;
            }
            set {
                this.fechaEnvioEncuestaField = value;
                this.RaisePropertyChanged("fechaEnvioEncuesta");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string fechaReenvioEncuesta {
            get {
                return this.fechaReenvioEncuestaField;
            }
            set {
                this.fechaReenvioEncuestaField = value;
                this.RaisePropertyChanged("fechaReenvioEncuesta");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public long msisdn {
            get {
                return this.msisdnField;
            }
            set {
                this.msisdnField = value;
                this.RaisePropertyChanged("msisdn");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool msisdnSpecified {
            get {
                return this.msisdnFieldSpecified;
            }
            set {
                this.msisdnFieldSpecified = value;
                this.RaisePropertyChanged("msisdnSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public long minContacto {
            get {
                return this.minContactoField;
            }
            set {
                this.minContactoField = value;
                this.RaisePropertyChanged("minContacto");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool minContactoSpecified {
            get {
                return this.minContactoFieldSpecified;
            }
            set {
                this.minContactoFieldSpecified = value;
                this.RaisePropertyChanged("minContactoSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public int telefonoLineaOrigen {
            get {
                return this.telefonoLineaOrigenField;
            }
            set {
                this.telefonoLineaOrigenField = value;
                this.RaisePropertyChanged("telefonoLineaOrigen");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool telefonoLineaOrigenSpecified {
            get {
                return this.telefonoLineaOrigenFieldSpecified;
            }
            set {
                this.telefonoLineaOrigenFieldSpecified = value;
                this.RaisePropertyChanged("telefonoLineaOrigenSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public int cuenta {
            get {
                return this.cuentaField;
            }
            set {
                this.cuentaField = value;
                this.RaisePropertyChanged("cuenta");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cuentaSpecified {
            get {
                return this.cuentaFieldSpecified;
            }
            set {
                this.cuentaFieldSpecified = value;
                this.RaisePropertyChanged("cuentaSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public int coId {
            get {
                return this.coIdField;
            }
            set {
                this.coIdField = value;
                this.RaisePropertyChanged("coId");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool coIdSpecified {
            get {
                return this.coIdFieldSpecified;
            }
            set {
                this.coIdFieldSpecified = value;
                this.RaisePropertyChanged("coIdSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string operacion {
            get {
                return this.operacionField;
            }
            set {
                this.operacionField = value;
                this.RaisePropertyChanged("operacion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string tipoLinea {
            get {
                return this.tipoLineaField;
            }
            set {
                this.tipoLineaField = value;
                this.RaisePropertyChanged("tipoLinea");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string segmento {
            get {
                return this.segmentoField;
            }
            set {
                this.segmentoField = value;
                this.RaisePropertyChanged("segmento");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public int tipoIdentificacion {
            get {
                return this.tipoIdentificacionField;
            }
            set {
                this.tipoIdentificacionField = value;
                this.RaisePropertyChanged("tipoIdentificacion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoIdentificacionSpecified {
            get {
                return this.tipoIdentificacionFieldSpecified;
            }
            set {
                this.tipoIdentificacionFieldSpecified = value;
                this.RaisePropertyChanged("tipoIdentificacionSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public long numeroIdentificacion {
            get {
                return this.numeroIdentificacionField;
            }
            set {
                this.numeroIdentificacionField = value;
                this.RaisePropertyChanged("numeroIdentificacion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numeroIdentificacionSpecified {
            get {
                return this.numeroIdentificacionFieldSpecified;
            }
            set {
                this.numeroIdentificacionFieldSpecified = value;
                this.RaisePropertyChanged("numeroIdentificacionSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string nombreCliente {
            get {
                return this.nombreClienteField;
            }
            set {
                this.nombreClienteField = value;
                this.RaisePropertyChanged("nombreCliente");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public int estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool estadoSpecified {
            get {
                return this.estadoFieldSpecified;
            }
            set {
                this.estadoFieldSpecified = value;
                this.RaisePropertyChanged("estadoSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string tokenId {
            get {
                return this.tokenIdField;
            }
            set {
                this.tokenIdField = value;
                this.RaisePropertyChanged("tokenId");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string causalesNoExito {
            get {
                return this.causalesNoExitoField;
            }
            set {
                this.causalesNoExitoField = value;
                this.RaisePropertyChanged("causalesNoExito");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public int idEncuesta {
            get {
                return this.idEncuestaField;
            }
            set {
                this.idEncuestaField = value;
                this.RaisePropertyChanged("idEncuesta");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idEncuestaSpecified {
            get {
                return this.idEncuestaFieldSpecified;
            }
            set {
                this.idEncuestaFieldSpecified = value;
                this.RaisePropertyChanged("idEncuestaSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string nombreEncuesta {
            get {
                return this.nombreEncuestaField;
            }
            set {
                this.nombreEncuestaField = value;
                this.RaisePropertyChanged("nombreEncuesta");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public int numeroReintentos {
            get {
                return this.numeroReintentosField;
            }
            set {
                this.numeroReintentosField = value;
                this.RaisePropertyChanged("numeroReintentos");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numeroReintentosSpecified {
            get {
                return this.numeroReintentosFieldSpecified;
            }
            set {
                this.numeroReintentosFieldSpecified = value;
                this.RaisePropertyChanged("numeroReintentosSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public string desReintentoFallido {
            get {
                return this.desReintentoFallidoField;
            }
            set {
                this.desReintentoFallidoField = value;
                this.RaisePropertyChanged("desReintentoFallido");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public string urlConexion {
            get {
                return this.urlConexionField;
            }
            set {
                this.urlConexionField = value;
                this.RaisePropertyChanged("urlConexion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=27)]
        public string usuarioRegistraSistema {
            get {
                return this.usuarioRegistraSistemaField;
            }
            set {
                this.usuarioRegistraSistemaField = value;
                this.RaisePropertyChanged("usuarioRegistraSistema");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicios.generacionencuestas.claro.com/")]
    public partial class respGenerarEncuesta : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codigoField;
        
        private bool codigoFieldSpecified;
        
        private string descripcionField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigoSpecified {
            get {
                return this.codigoFieldSpecified;
            }
            set {
                this.codigoFieldSpecified = value;
                this.RaisePropertyChanged("codigoSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="enviarEncuesta", WrapperNamespace="http://servicios.generacionencuestas.claro.com/", IsWrapped=true)]
    internal partial class enviarEncuestaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.generacionencuestas.claro.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Dime.WSP.reqGenerarEncuesta ReqEnviarEncuesta;
        
        public enviarEncuestaRequest() {
        }
        
        public enviarEncuestaRequest(Dime.WSP.reqGenerarEncuesta ReqEnviarEncuesta) {
            this.ReqEnviarEncuesta = ReqEnviarEncuesta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="enviarEncuestaResponse", WrapperNamespace="http://servicios.generacionencuestas.claro.com/", IsWrapped=true)]
    internal partial class enviarEncuestaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.generacionencuestas.claro.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Dime.WSP.respGenerarEncuesta RespGenerarEncuesta;
        
        public enviarEncuestaResponse() {
        }
        
        public enviarEncuestaResponse(Dime.WSP.respGenerarEncuesta RespGenerarEncuesta) {
            this.RespGenerarEncuesta = RespGenerarEncuesta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registrarLog", WrapperNamespace="http://servicios.generacionencuestas.claro.com/", IsWrapped=true)]
    internal partial class registrarLogRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.generacionencuestas.claro.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Dime.WSP.reqGenerarLog ReqGenerarLog;
        
        public registrarLogRequest() {
        }
        
        public registrarLogRequest(Dime.WSP.reqGenerarLog ReqGenerarLog) {
            this.ReqGenerarLog = ReqGenerarLog;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registrarLogResponse", WrapperNamespace="http://servicios.generacionencuestas.claro.com/", IsWrapped=true)]
    internal partial class registrarLogResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.generacionencuestas.claro.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Dime.WSP.RespConsultarParamCobranza RespGenerarLog;
        
        public registrarLogResponse() {
        }
        
        public registrarLogResponse(Dime.WSP.RespConsultarParamCobranza RespGenerarLog) {
            this.RespGenerarLog = RespGenerarLog;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="resetPropiedades", WrapperNamespace="http://servicios.generacionencuestas.claro.com/", IsWrapped=true)]
    internal partial class resetPropiedadesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.generacionencuestas.claro.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.generacionencuestas.claro.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string psw;
        
        public resetPropiedadesRequest() {
        }
        
        public resetPropiedadesRequest(string usuario, string psw) {
            this.usuario = usuario;
            this.psw = psw;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="resetPropiedadesResponse", WrapperNamespace="http://servicios.generacionencuestas.claro.com/", IsWrapped=true)]
    internal partial class resetPropiedadesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.generacionencuestas.claro.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Respuesta;
        
        public resetPropiedadesResponse() {
        }
        
        public resetPropiedadesResponse(string Respuesta) {
            this.Respuesta = Respuesta;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal interface GeneracionEncuestaChannel : Dime.WSP.GeneracionEncuesta, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal partial class GeneracionEncuestaClient : System.ServiceModel.ClientBase<Dime.WSP.GeneracionEncuesta>, Dime.WSP.GeneracionEncuesta {
        
        public GeneracionEncuestaClient() {
        }
        
        public GeneracionEncuestaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GeneracionEncuestaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GeneracionEncuestaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GeneracionEncuestaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Dime.WSP.enviarEncuestaResponse Dime.WSP.GeneracionEncuesta.enviarEncuesta(Dime.WSP.enviarEncuestaRequest request) {
            return base.Channel.enviarEncuesta(request);
        }
        
        public Dime.WSP.respGenerarEncuesta enviarEncuesta(Dime.WSP.reqGenerarEncuesta ReqEnviarEncuesta) {
            Dime.WSP.enviarEncuestaRequest inValue = new Dime.WSP.enviarEncuestaRequest();
            inValue.ReqEnviarEncuesta = ReqEnviarEncuesta;
            Dime.WSP.enviarEncuestaResponse retVal = ((Dime.WSP.GeneracionEncuesta)(this)).enviarEncuesta(inValue);
            return retVal.RespGenerarEncuesta;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Dime.WSP.enviarEncuestaResponse> Dime.WSP.GeneracionEncuesta.enviarEncuestaAsync(Dime.WSP.enviarEncuestaRequest request) {
            return base.Channel.enviarEncuestaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Dime.WSP.enviarEncuestaResponse> enviarEncuestaAsync(Dime.WSP.reqGenerarEncuesta ReqEnviarEncuesta) {
            Dime.WSP.enviarEncuestaRequest inValue = new Dime.WSP.enviarEncuestaRequest();
            inValue.ReqEnviarEncuesta = ReqEnviarEncuesta;
            return ((Dime.WSP.GeneracionEncuesta)(this)).enviarEncuestaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Dime.WSP.registrarLogResponse Dime.WSP.GeneracionEncuesta.registrarLog(Dime.WSP.registrarLogRequest request) {
            return base.Channel.registrarLog(request);
        }
        
        public Dime.WSP.RespConsultarParamCobranza registrarLog(Dime.WSP.reqGenerarLog ReqGenerarLog) {
            Dime.WSP.registrarLogRequest inValue = new Dime.WSP.registrarLogRequest();
            inValue.ReqGenerarLog = ReqGenerarLog;
            Dime.WSP.registrarLogResponse retVal = ((Dime.WSP.GeneracionEncuesta)(this)).registrarLog(inValue);
            return retVal.RespGenerarLog;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Dime.WSP.registrarLogResponse> Dime.WSP.GeneracionEncuesta.registrarLogAsync(Dime.WSP.registrarLogRequest request) {
            return base.Channel.registrarLogAsync(request);
        }
        
        public System.Threading.Tasks.Task<Dime.WSP.registrarLogResponse> registrarLogAsync(Dime.WSP.reqGenerarLog ReqGenerarLog) {
            Dime.WSP.registrarLogRequest inValue = new Dime.WSP.registrarLogRequest();
            inValue.ReqGenerarLog = ReqGenerarLog;
            return ((Dime.WSP.GeneracionEncuesta)(this)).registrarLogAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Dime.WSP.resetPropiedadesResponse Dime.WSP.GeneracionEncuesta.resetPropiedades(Dime.WSP.resetPropiedadesRequest request) {
            return base.Channel.resetPropiedades(request);
        }
        
        public string resetPropiedades(string usuario, string psw) {
            Dime.WSP.resetPropiedadesRequest inValue = new Dime.WSP.resetPropiedadesRequest();
            inValue.usuario = usuario;
            inValue.psw = psw;
            Dime.WSP.resetPropiedadesResponse retVal = ((Dime.WSP.GeneracionEncuesta)(this)).resetPropiedades(inValue);
            return retVal.Respuesta;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Dime.WSP.resetPropiedadesResponse> Dime.WSP.GeneracionEncuesta.resetPropiedadesAsync(Dime.WSP.resetPropiedadesRequest request) {
            return base.Channel.resetPropiedadesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Dime.WSP.resetPropiedadesResponse> resetPropiedadesAsync(string usuario, string psw) {
            Dime.WSP.resetPropiedadesRequest inValue = new Dime.WSP.resetPropiedadesRequest();
            inValue.usuario = usuario;
            inValue.psw = psw;
            return ((Dime.WSP.GeneracionEncuesta)(this)).resetPropiedadesAsync(inValue);
        }
    }
}
