// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning
using System;

namespace Telmexla.Servicios.DIME.Entity
{

    public class CierreCiclo
    {
        public int Id { get; set; } // ID (Primary key)
        public System.DateTime? FechaGestion { get; set; } // FECHA_GESTION
        public string UsuarioGestion { get; set; } // USUARIO_GESTION (length: 50)
        public string AliadoGestion { get; set; } // ALIADO_GESTION (length: 50)
        public double? Cuenta { get; set; } // CUENTA
        public decimal? Ofrecimiento1 { get; set; } // OFRECIMIENTO_1
        public decimal? Ofrecimiento2 { get; set; } // OFRECIMIENTO_2
        public decimal? Ofrecimiento3 { get; set; } // OFRECIMIENTO_3
        public decimal? PServicio1 { get; set; } // P_SERVICIO_1
        public decimal? PServicio2 { get; set; } // P_SERVICIO_2
        public decimal? PServicio3 { get; set; } // P_SERVICIO_3
        public decimal? PServicio4 { get; set; } // P_SERVICIO_4
        public decimal? PServicio5 { get; set; } // P_SERVICIO_5
        public decimal? PServicio6 { get; set; } // P_SERVICIO_6
        public decimal? PServicio7 { get; set; } // P_SERVICIO_7
        public decimal? PServicio8 { get; set; } // P_SERVICIO_8
        public decimal? PServicio9 { get; set; } // P_SERVICIO_9
        public decimal? PServicio10 { get; set; } // P_SERVICIO_10
        public decimal? PServicio11 { get; set; } // P_SERVICIO_11
        public decimal? PServicio12 { get; set; } // P_SERVICIO_12
        public decimal? PServicio13 { get; set; } // P_SERVICIO_13
        public decimal? PServicio14 { get; set; } // P_SERVICIO_14
        public decimal? PServicio15 { get; set; } // P_SERVICIO_15
        public decimal? PServicio16 { get; set; } // P_SERVICIO_16
        public decimal? PServicio17 { get; set; } // P_SERVICIO_17
        public decimal? PServicio18 { get; set; } // P_SERVICIO_18
        public decimal? PServicio19 { get; set; } // P_SERVICIO_19
        public decimal? PServicio20 { get; set; } // P_SERVICIO_20
        public decimal? PServicio21 { get; set; } // P_SERVICIO_21
        public decimal? PServicio22 { get; set; } // P_SERVICIO_22
        public decimal? PServicio23 { get; set; } // P_SERVICIO_23
        public decimal? PServicio24 { get; set; } // P_SERVICIO_24
        public decimal? PServicio25 { get; set; } // P_SERVICIO_25
        public decimal? PServicio26 { get; set; } // P_SERVICIO_26
        public decimal? PServicio27 { get; set; } // P_SERVICIO_27
        public decimal? PServicio28 { get; set; } // P_SERVICIO_28
        public decimal? PServicio29 { get; set; } // P_SERVICIO_29
        public decimal? PServicio30 { get; set; } // P_SERVICIO_30
        public decimal? PServicio31 { get; set; } // P_SERVICIO_31
        public decimal? PServicio32 { get; set; } // P_SERVICIO_32
        public decimal? PServicio33 { get; set; } // P_SERVICIO_33
        public decimal? PServicio34 { get; set; } // P_SERVICIO_34
        public decimal? PServicio35 { get; set; } // P_SERVICIO_35
        public decimal? PServicio36 { get; set; } // P_SERVICIO_36
        public string TipoContacto { get; set; } // TIPO_CONTACTO (length: 50)
        public string Gestion { get; set; } // GESTION (length: 100)
        public string Cierre { get; set; } // CIERRE (length: 100)
        public string Razon { get; set; } // RAZON (length: 100)
        public string Obervaciones { get; set; } // OBERVACIONES (length: 1000)
        public string Base { get; set; } // BASE (length: 50)
        public string OperacionGestion { get; set; } // OPERACION_GESTION (length: 50)
        public string Motivo { get; set; } // MOTIVO (length: 100)
        public string Seguimiento { get; set; } // SEGUIMIENTO (length: 2)
        public System.DateTime? FechaSeguimiento { get; set; } // FECHA_SEGUIMIENTO

        public string NombreCliente { get; set; }

        public bool checkBOfrecimiento1
        {
            get { return Convert.ToBoolean(Ofrecimiento1); }
            set { Ofrecimiento1 = Convert.ToDecimal(value); }
        }
        public bool checkBOfrecimiento2
        {
            get { return Convert.ToBoolean(Ofrecimiento2); }
            set { Ofrecimiento2 = Convert.ToDecimal(value); }
        }

        public bool checkBOfrecimiento3
        {
            get { return Convert.ToBoolean(Ofrecimiento3); }
            set { Ofrecimiento3 = Convert.ToDecimal(value); }
        }

        public bool checkBPServicio1
        {
            get { return Convert.ToBoolean(PServicio1); }
            set { PServicio1 = Convert.ToDecimal(value); }
        }
        public bool checkBPServicio2
        {
            get { return Convert.ToBoolean(PServicio2); }
            set { PServicio2 = Convert.ToDecimal(value); }
        }
        public bool checkBPServicio3
        {
            get { return Convert.ToBoolean(PServicio3); }
            set { PServicio3 = Convert.ToDecimal(value); }
        }
        public bool checkBPServicio4
        {
            get { return Convert.ToBoolean(PServicio4); }
            set { PServicio4 = Convert.ToDecimal(value); }
        }
        public bool checkBPServicio5
        {
            get { return Convert.ToBoolean(PServicio5); }
            set { PServicio5 = Convert.ToDecimal(value); }
        }
        public bool checkBPServicio6
        {
            get { return Convert.ToBoolean(PServicio6); }
            set { PServicio6 = Convert.ToDecimal(value); }
        }
        public bool checkBPServicio7
        {
            get { return Convert.ToBoolean(PServicio7); }
            set { PServicio7 = Convert.ToDecimal(value); }
        }
        public bool checkBPServicio8
        {
            get { return Convert.ToBoolean(PServicio8); }
            set { PServicio8 = Convert.ToDecimal(value); }
        }
        public bool checkBPServicio9
        {
            get { return Convert.ToBoolean(PServicio9); }
            set { PServicio9 = Convert.ToDecimal(value); }
        }
        public bool checkBPServicio10
        {
            get { return Convert.ToBoolean(PServicio10); }
            set { PServicio10 = Convert.ToDecimal(value); }
        }
        public bool checkBPServicio11
        {
            get { return Convert.ToBoolean(PServicio11); }
            set { PServicio11 = Convert.ToDecimal(value); }
        }
        public bool checkBPServicio12
        {
            get { return Convert.ToBoolean(PServicio12); }
            set { PServicio12 = Convert.ToDecimal(value); }
        }
        public bool checkBPServicio13
        {
            get { return Convert.ToBoolean(PServicio13); }
            set { PServicio13 = Convert.ToDecimal(value); }
        }
        public bool checkBPServicio14
        {
            get { return Convert.ToBoolean(PServicio14); }
            set { PServicio14 = Convert.ToDecimal(value); }
        }
        public bool checkBPServicio15
        {
            get { return Convert.ToBoolean(PServicio15); }
            set { PServicio15 = Convert.ToDecimal(value); }
        }
        public bool checkBPServicio16
        {
            get { return Convert.ToBoolean(PServicio16); }
            set { PServicio16 = Convert.ToDecimal(value); }
        }
        public bool checkBPServicio17
        {
            get { return Convert.ToBoolean(PServicio17); }
            set { PServicio17 = Convert.ToDecimal(value); }
        }
        public bool checkBPServicio18
        {
            get { return Convert.ToBoolean(PServicio18); }
            set { PServicio18 = Convert.ToDecimal(value); }
        }
        public bool checkBPServicio19
        {
            get { return Convert.ToBoolean(PServicio19); }
            set { PServicio19 = Convert.ToDecimal(value); }
        }
        public bool checkBPServicio20
        {
            get { return Convert.ToBoolean(PServicio20); }
            set { PServicio20 = Convert.ToDecimal(value); }
        }
        public bool checkBPServicio21
        {
            get { return Convert.ToBoolean(PServicio21); }
            set { PServicio21 = Convert.ToDecimal(value); }
        }
        public bool checkBPServicio22
        {
            get { return Convert.ToBoolean(PServicio22); }
            set { PServicio22= Convert.ToDecimal(value); }
        }
        public bool checkBPServicio23
        {
            get { return Convert.ToBoolean(PServicio23); }
            set { PServicio23 = Convert.ToDecimal(value); }
        }
        public bool checkBPServicio24
        {
            get { return Convert.ToBoolean(PServicio24); }
            set { PServicio24 = Convert.ToDecimal(value); }
        }
        public bool checkBPServicio25
        {
            get { return Convert.ToBoolean(PServicio25); }
            set { PServicio25 = Convert.ToDecimal(value); }
        }
        public bool checkBPServicio26
        {
            get { return Convert.ToBoolean(PServicio26); }
            set { PServicio26 = Convert.ToDecimal(value); }
        }
        public bool checkBPServicio27
        {
            get { return Convert.ToBoolean(PServicio27); }
            set { PServicio27 = Convert.ToDecimal(value); }
        }
        public bool checkBPServicio28
        {
            get { return Convert.ToBoolean(PServicio28); }
            set { PServicio28 = Convert.ToDecimal(value); }
        }
        public bool checkBPServicio29
        {
            get { return Convert.ToBoolean(PServicio29); }
            set { PServicio29 = Convert.ToDecimal(value); }
        }
        public bool checkBPServicio30
        {
            get { return Convert.ToBoolean(PServicio30); }
            set { PServicio30 = Convert.ToDecimal(value); }
        }
        public bool checkBPServicio31
        {
            get { return Convert.ToBoolean(PServicio31); }
            set { PServicio31 = Convert.ToDecimal(value); }
        }
        public bool checkBPServicio32
        {
            get { return Convert.ToBoolean(PServicio32); }
            set { PServicio32 = Convert.ToDecimal(value); }
        }
        public bool checkBPServicio33
        {
            get { return Convert.ToBoolean(PServicio33); }
            set { PServicio33 = Convert.ToDecimal(value); }
        }
        public bool checkBPServicio34
        {
            get { return Convert.ToBoolean(PServicio34); }
            set { PServicio34 = Convert.ToDecimal(value); }
        }
        public bool checkBPServicio35
        {
            get { return Convert.ToBoolean(PServicio35); }
            set { PServicio35 = Convert.ToDecimal(value); }
        }
        public bool checkBPServicio36
        {
            get { return Convert.ToBoolean(PServicio36); }
            set { PServicio36 = Convert.ToDecimal(value); }
        }



    }

}
// </auto-generated>
